In [57]:
import os
os.chdir("C:/Users/zemar/OneDrive/Documentos")
from si.src.data.dataset import Dataset
import numpy as np   
from si.src.neural_networks.layers import Layer, DenseLayer, Dropout
from si.src.neural_networks.neural_network import NeuralNetwork
from si.src.neural_networks.optimizers import SGD, Adam
from si.src.neural_networks.activation import ReLUActivation,SigmoidActivation, TanhActivation, SoftmaxActivation
from si.src.neural_networks.losses import BinaryCrossEntropy
from si.src.model_selection.split import stratified_train_test_split, train_test_split
from si.src.metrics.accuracy import accuracy
import matplotlib.pyplot as plt
from si.src.neural_networks.losses import CategoricalCrossEntropy

EX 12

In [7]:
np.random.seed(42)
x = np.array([[1,2,3,4,5,6,7,8,9,10]])
print("x:", x)
dropout = Dropout(0.5)
print("output training:", dropout.forward_propagation(x, training=True))
print("mask:", dropout.mask)

print("output inference:", dropout.forward_propagation(x, training=False))

x: [[ 1  2  3  4  5  6  7  8  9 10]]
output training: [[ 0.  4.  6.  8.  0.  0.  0. 16. 18. 20.]]
mask: [[0 1 1 1 0 0 0 1 1 1]]
output inference: [[ 1  2  3  4  5  6  7  8  9 10]]


EX 13

EX 13.2

In [15]:
softmax_activation = SoftmaxActivation()

scores2D = np.array([[4, 2, 3, 6],
                     [2, 1, 5, 6],
                     [3, 8, 7, 4]])

print(softmax_activation.activation_function(scores2D))
print(np.sum(softmax_activation.activation_function(scores2D), axis=1))

[[0.11245721 0.01521943 0.0413707  0.83095266]
 [0.01314897 0.00483724 0.26410418 0.71790961]
 [0.00483724 0.71790961 0.26410418 0.01314897]]
[1. 1. 1.]


14

In [18]:
cross_entropy_loss = CategoricalCrossEntropy()

# Generate input values
x_values = np.array([[1,2,3], [4,5,6], [7,8,9]])
y_values = np.array([[1.9,2.9,3.9], [4.9,5.9,6.9], [7.9,8.9,9.9]])


# Calculate loss for each input-target pair
loss = cross_entropy_loss.loss(x_values, y_values)
derivative = cross_entropy_loss.derivative(x_values, y_values)

print(loss)
print(derivative)

4.496403249731887e-14
[[-1. -2. -3.]
 [-4. -5. -6.]
 [-7. -8. -9.]]


15

In [22]:
weights = np.array([6, 7, 8, 9, 10])
grad_loss_weights = np.array([0.1, 0.2, 0.3, 0.4, 0.5])

#comparison
for x in [0.01, 0.1, 0.5]:
    adam_optimizer = Adam(learning_rate=x)
    updated_w_adam = adam_optimizer.update(weights, grad_loss_weights)
    print(f"Learing Rate {x}:", updated_w_adam)

Learing Rate 0.01: [5.99 6.99 7.99 8.99 9.99]
Learing Rate 0.1: [5.90000001 6.9        7.9        8.9        9.9       ]
Learing Rate 0.5: [5.50000005 6.50000002 7.50000002 8.50000001 9.50000001]


16

In [61]:
#create the dataset
np.random.seed(42)
X = np.random.randn(160, 32)  # 160 amostras, 32 características
y = np.random.randint(2, size=(160, 1))  #  binários (0 ou 1)
dataset=Dataset(X=X,y=y)

#divide the dataset
train_dl,test_dl = train_test_split(dataset, test_size=0.2, random_state=42)

#create the neural network
model_dl =NeuralNetwork(epochs=100, batch_size=16, optimizer=SGD, learning_rate=0.01, verbose=True, loss=BinaryCrossEntropy, metric=accuracy)
n_features = X.shape[1]
model_dl.add(DenseLayer(32, (n_features,)))
model_dl.add(ReLUActivation())
model_dl.add(DenseLayer(16))
model_dl.add(ReLUActivation())
model_dl.add(DenseLayer(1))
model_dl.add(SigmoidActivation())

#train the model
model_dl.fit(train_dl)

Epoch 1/100 - loss: 117.5909 - accuracy: 0.0000
Epoch 2/100 - loss: 90.0337 - accuracy: 0.0000
Epoch 3/100 - loss: 82.8328 - accuracy: 0.0000
Epoch 4/100 - loss: 79.0319 - accuracy: 0.0000
Epoch 5/100 - loss: 73.5169 - accuracy: 0.0000
Epoch 6/100 - loss: 69.5928 - accuracy: 0.0000
Epoch 7/100 - loss: 61.9997 - accuracy: 0.0000
Epoch 8/100 - loss: 56.5251 - accuracy: 0.0000
Epoch 9/100 - loss: 50.6257 - accuracy: 0.0000
Epoch 10/100 - loss: 43.7767 - accuracy: 0.0000
Epoch 11/100 - loss: 37.3012 - accuracy: 0.0000
Epoch 12/100 - loss: 31.5761 - accuracy: 0.0000
Epoch 13/100 - loss: 26.9250 - accuracy: 0.0000
Epoch 14/100 - loss: 22.8125 - accuracy: 0.0000
Epoch 15/100 - loss: 18.0815 - accuracy: 0.0000
Epoch 16/100 - loss: 14.7586 - accuracy: 0.0000
Epoch 17/100 - loss: 12.3111 - accuracy: 0.0000
Epoch 18/100 - loss: 10.1040 - accuracy: 0.0000
Epoch 19/100 - loss: 8.6971 - accuracy: 0.0000
Epoch 20/100 - loss: 7.6421 - accuracy: 0.0000
Epoch 21/100 - loss: 6.4670 - accuracy: 0.0000
Epo

0.0
