testing new methods


In [19]:
import os
os.chdir("C:/Users/zemar/OneDrive/Documentos")
import numpy as np

In [20]:
from si.src.data.dataset import Dataset

X = np.array([[1, 2, 3], [4, 5, 6], [6, 7, np.nan]])
y = np.array([1, 2, 3])
features = np.array(['a', 'b', 'c'])
label = 'y'
dataset = Dataset(X, y, features, label)

print(dataset.X)



[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 6.  7. nan]]


In [21]:
dataset.dropna()
print(dataset.X)

[[1. 2. 3.]
 [4. 5. 6.]]


In [22]:
X = np.array([[6, 2, 3], [9, 5, 1], [6, 7, np.nan]])
y = np.array([1, 2, 3])
features = np.array(['a', 'b', 'c'])
label = 'y'
dataset = Dataset(X, y, features, label)

print(dataset.X)
print()
dataset.fillna(1)
print(dataset.X)



[[ 6.  2.  3.]
 [ 9.  5.  1.]
 [ 6.  7. nan]]

[[6. 2. 3.]
 [9. 5. 1.]
 [6. 7. 1.]]


In [23]:

print(dataset.X)
print()
dataset.fillna('median')
print(dataset.X)


[[6. 2. 3.]
 [9. 5. 1.]
 [6. 7. 1.]]

[[6. 2. 3.]
 [9. 5. 1.]
 [6. 7. 1.]]


In [24]:
print(dataset.X)
print()
dataset.fillna('mean')
print(dataset.X)

[[6. 2. 3.]
 [9. 5. 1.]
 [6. 7. 1.]]

[[6. 2. 3.]
 [9. 5. 1.]
 [6. 7. 1.]]


In [26]:
X = np.array([[7, 2, 3], [8, 5, 6], [6, 7, np.nan]])
y = np.array([1, 2, 3])
features = np.array(['a', 'b', 'c'])
label = 'y'
dataset = Dataset(X, y, features, label)

print(dataset.X)
print()
dataset.remove_by_index(1)
print(dataset.X)

[[ 7.  2.  3.]
 [ 8.  5.  6.]
 [ 6.  7. nan]]

[[ 7.  2.  3.]
 [ 6.  7. nan]]
