EX 4


In [2]:
import os
os.chdir("C:/Users/zemar/OneDrive/Documentos")

from si.src.statistics.manhattan_distance import manhattan_distance
import numpy as np

x = np.array([1, 2, 3])
y = np.array([[4, 5, 6], [7, 8, 9]])
md = manhattan_distance(x, y)

#sklearn package
from sklearn.metrics.pairwise import manhattan_distances
sklearn_md = manhattan_distances([x], y)

print("My distance:", md)
print("Sklearn distance:", sklearn_md)

My distance: [ 9 18]
Sklearn distance: [[ 9. 18.]]


EX 5

In [11]:
from si.src.io.csv_file import read_csv
from si.src.decomposition.PCA import PCA
iris = read_csv('si/datasets/iris/iris.csv',sep=',',features=True, label=True)

#float (0.95) n_components
pca = PCA(n_components=0.95)
pca.fit_transform(iris)
print('components:', pca.components)
print('explained variance:', pca.explained_var)
print('explained variance ratio:',pca.explained_var_ratio)
print()

#int (2) n_components
pca = PCA(n_components=2)
pca.fit_transform(iris)
print('comps:', pca.components)
print('explained var:', pca.explained_var)
print('explained var ratio:', pca.explained_var_ratio)

float (0.95) n_components:
components: [[ 0.36158968 -0.08226889  0.85657211  0.35884393]
 [-0.65653988 -0.72971237  0.1757674   0.07470647]]
explained variance: [4.22484077 0.24224357]
explained variance ratio: [0.94577144 0.05422856]

int (2) n_components:
components: [[ 0.36158968 -0.08226889  0.85657211  0.35884393]
 [-0.65653988 -0.72971237  0.1757674   0.07470647]]
explained variance: [4.22484077 0.24224357]
explained variance ratio: [0.94577144 0.05422856]


In [16]:
#MEAN
pca.mean

array([5.84333333, 3.054     , 3.75866667, 1.19866667])

comparing to sklearn module

In [17]:
from sklearn.decomposition import PCA as skPCA

pca = skPCA(n_components=0.95)
pca.fit_transform(iris.X)
print('comps:', pca.components_)
print('explained var:', pca.explained_variance_)
print('explained var ratio:',pca.explained_variance_ratio_)
print()

pca = skPCA(n_components=2)
pca.fit_transform(iris.X)
print('comps:', pca.components_)
print('explained var:', pca.explained_variance_)
print('explained var ratio:', pca.explained_variance_ratio_)

comps: [[ 0.36158968 -0.08226889  0.85657211  0.35884393]
 [ 0.65653988  0.72971237 -0.1757674  -0.07470647]]
explained var: [4.22484077 0.24224357]
explained var ratio: [0.92461621 0.05301557]

comps: [[ 0.36158968 -0.08226889  0.85657211  0.35884393]
 [ 0.65653988  0.72971237 -0.1757674  -0.07470647]]
explained var: [4.22484077 0.24224357]
explained var ratio: [0.92461621 0.05301557]
